
package tema9.interfaces;

/**
 *
 * @author Ruper
 */
public class Calculadora_V0 extends javax.swing.JFrame {
    // Variables para almacenar valores y operación
    private double firstNumber;
    private double secondNumber;
    private String operation;
    
    /**
     * Creates new form Calculadora_V0
     */
    public Calculadora_V0() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_1 = new javax.swing.JButton();
        bt_2 = new javax.swing.JButton();
        bt_3 = new javax.swing.JButton();
        bt_4 = new javax.swing.JButton();
        bt_5 = new javax.swing.JButton();
        bt_7 = new javax.swing.JButton();
        bt_8 = new javax.swing.JButton();
        bt_9 = new javax.swing.JButton();
        bt_0 = new javax.swing.JButton();
        bt_Clear = new javax.swing.JButton();
        bt_Dividir = new javax.swing.JButton();
        bt_Multiplicar = new javax.swing.JButton();
        bt_Sumar = new javax.swing.JButton();
        bt_Restar = new javax.swing.JButton();
        bt_Resultado = new javax.swing.JButton();
        bt_6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_Display = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        bt_Cuadrado = new javax.swing.JButton();
        bt_Inverso = new javax.swing.JButton();
        bt_RaizCuadrada = new javax.swing.JButton();
        bt_CE = new javax.swing.JButton();
        bt_Porcentaje = new javax.swing.JButton();
        bt_CambiarSigno = new javax.swing.JButton();
        bt_Decimal = new javax.swing.JButton();
        bt_Borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_1.setText("1");
        bt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_1ActionPerformed(evt);
            }
        });

        bt_2.setText("2");
        bt_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_2ActionPerformed(evt);
            }
        });

        bt_3.setText("3");
        bt_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_3ActionPerformed(evt);
            }
        });

        bt_4.setText("4");
        bt_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_4ActionPerformed(evt);
            }
        });

        bt_5.setText("5");
        bt_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_5ActionPerformed(evt);
            }
        });

        bt_7.setText("7");
        bt_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_7ActionPerformed(evt);
            }
        });

        bt_8.setText("8");
        bt_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_8ActionPerformed(evt);
            }
        });

        bt_9.setText("9");
        bt_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_9ActionPerformed(evt);
            }
        });

        bt_0.setText("0");
        bt_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_0ActionPerformed(evt);
            }
        });

        bt_Clear.setText("C");
        bt_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ClearActionPerformed(evt);
            }
        });

        bt_Dividir.setText("/");
        bt_Dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_DividirActionPerformed(evt);
            }
        });

        bt_Multiplicar.setText("*");
        bt_Multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_MultiplicarActionPerformed(evt);
            }
        });

        bt_Sumar.setText("+");
        bt_Sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SumarActionPerformed(evt);
            }
        });

        bt_Restar.setText("-");
        bt_Restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_RestarActionPerformed(evt);
            }
        });

        bt_Resultado.setText("=");
        bt_Resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ResultadoActionPerformed(evt);
            }
        });

        bt_6.setText("6");
        bt_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_6ActionPerformed(evt);
            }
        });

        ta_Display.setEditable(false);
        ta_Display.setColumns(20);
        ta_Display.setRows(5);
        jScrollPane1.setViewportView(ta_Display);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CALCULADORA");

        bt_Cuadrado.setText("x²");
        bt_Cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CuadradoActionPerformed(evt);
            }
        });

        bt_Inverso.setText("1/x");
        bt_Inverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_InversoActionPerformed(evt);
            }
        });

        bt_RaizCuadrada.setText("√x");
        bt_RaizCuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_RaizCuadradaActionPerformed(evt);
            }
        });

        bt_CE.setText("CE");
        bt_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CEActionPerformed(evt);
            }
        });

        bt_Porcentaje.setText("%");
        bt_Porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_PorcentajeActionPerformed(evt);
            }
        });

        bt_CambiarSigno.setText("±");
        bt_CambiarSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CambiarSignoActionPerformed(evt);
            }
        });

        bt_Decimal.setText(",");
        bt_Decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_DecimalActionPerformed(evt);
            }
        });

        bt_Borrar.setText("⌫");
        bt_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_BorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bt_Porcentaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_Inverso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_CambiarSigno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bt_0, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(bt_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_Cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(bt_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bt_Clear, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(bt_RaizCuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(bt_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_Decimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bt_Borrar, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(bt_Dividir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_Multiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_Restar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_Sumar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_Resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Clear)
                    .addComponent(bt_CE)
                    .addComponent(bt_Porcentaje)
                    .addComponent(bt_Borrar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Dividir)
                    .addComponent(bt_Cuadrado)
                    .addComponent(bt_Inverso)
                    .addComponent(bt_RaizCuadrada))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_9)
                    .addComponent(bt_8)
                    .addComponent(bt_7)
                    .addComponent(bt_Multiplicar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_6)
                    .addComponent(bt_5)
                    .addComponent(bt_4)
                    .addComponent(bt_Restar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Sumar)
                    .addComponent(bt_3)
                    .addComponent(bt_2)
                    .addComponent(bt_1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Resultado)
                    .addComponent(bt_0)
                    .addComponent(bt_CambiarSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Decimal))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_0ActionPerformed
        ta_Display.append("0");
    }//GEN-LAST:event_bt_0ActionPerformed

    private void bt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_1ActionPerformed
        ta_Display.append("1");
    }//GEN-LAST:event_bt_1ActionPerformed

    private void bt_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_2ActionPerformed
        ta_Display.append("2");
    }//GEN-LAST:event_bt_2ActionPerformed

    private void bt_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_3ActionPerformed
        ta_Display.append("3");
    }//GEN-LAST:event_bt_3ActionPerformed

    private void bt_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_4ActionPerformed
        ta_Display.append("4");
    }//GEN-LAST:event_bt_4ActionPerformed

    private void bt_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_5ActionPerformed
        ta_Display.append("5");
    }//GEN-LAST:event_bt_5ActionPerformed

    private void bt_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_6ActionPerformed
        ta_Display.append("6");
    }//GEN-LAST:event_bt_6ActionPerformed

    private void bt_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_7ActionPerformed
        ta_Display.append("7");
    }//GEN-LAST:event_bt_7ActionPerformed

    private void bt_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_8ActionPerformed
        ta_Display.append("8");
    }//GEN-LAST:event_bt_8ActionPerformed

    private void bt_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_9ActionPerformed
        ta_Display.append("9");
    }//GEN-LAST:event_bt_9ActionPerformed

    private void bt_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ClearActionPerformed
        ta_Display.setText("");
    }//GEN-LAST:event_bt_ClearActionPerformed

    private void bt_SumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SumarActionPerformed
        firstNumber = Double.parseDouble(ta_Display.getText());
        ta_Display.setText("");
        operation = "+";
    }//GEN-LAST:event_bt_SumarActionPerformed

    private void bt_RestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_RestarActionPerformed
        firstNumber = Double.parseDouble(ta_Display.getText());
        ta_Display.setText("");
        operation = "-";
    }//GEN-LAST:event_bt_RestarActionPerformed

    private void bt_DividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_DividirActionPerformed
        firstNumber = Double.parseDouble(ta_Display.getText());
        ta_Display.setText("");
        operation = "/";
    }//GEN-LAST:event_bt_DividirActionPerformed

    private void bt_MultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_MultiplicarActionPerformed
        firstNumber = Double.parseDouble(ta_Display.getText());
        ta_Display.setText("");
        operation = "*";
    }//GEN-LAST:event_bt_MultiplicarActionPerformed

    private void bt_ResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ResultadoActionPerformed
        secondNumber = Double.parseDouble(ta_Display.getText());
        switch (operation) {
            case "+":
                ta_Display.setText(Double.toString(firstNumber + secondNumber));
                break;
            case "-":
                ta_Display.setText(Double.toString(firstNumber - secondNumber));
                break;
            case "*":
                ta_Display.setText(Double.toString(firstNumber * secondNumber));
                break;
            case "/":
                ta_Display.setText(Double.toString(firstNumber / secondNumber));
                break;
        }
    }//GEN-LAST:event_bt_ResultadoActionPerformed

    private void bt_RaizCuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_RaizCuadradaActionPerformed
        double value = Double.parseDouble(ta_Display.getText());
        ta_Display.setText(Double.toString(Math.sqrt(value)));
    }//GEN-LAST:event_bt_RaizCuadradaActionPerformed

    private void bt_CuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CuadradoActionPerformed
        double value = Double.parseDouble(ta_Display.getText());
        ta_Display.setText(Double.toString(value * value));
    }//GEN-LAST:event_bt_CuadradoActionPerformed

    private void bt_InversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_InversoActionPerformed
        double value = Double.parseDouble(ta_Display.getText());
        ta_Display.setText(Double.toString(1 / value));
    }//GEN-LAST:event_bt_InversoActionPerformed

    private void bt_PorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_PorcentajeActionPerformed
        double value = Double.parseDouble(ta_Display.getText());
        ta_Display.setText(Double.toString(value / 100));
    }//GEN-LAST:event_bt_PorcentajeActionPerformed

    private void bt_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CEActionPerformed
        ta_Display.setText("");
    }//GEN-LAST:event_bt_CEActionPerformed

    private void bt_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_BorrarActionPerformed
        String text = ta_Display.getText();
        if (text.length() > 0) {
            ta_Display.setText(text.substring(0, text.length() - 1));
        }
    }//GEN-LAST:event_bt_BorrarActionPerformed

    private void bt_CambiarSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CambiarSignoActionPerformed
        double value = Double.parseDouble(ta_Display.getText());
        ta_Display.setText(Double.toString(-value));
    }//GEN-LAST:event_bt_CambiarSignoActionPerformed

    private void bt_DecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_DecimalActionPerformed
        if (!ta_Display.getText().contains(".")) {
            ta_Display.append(".");
        }
    }//GEN-LAST:event_bt_DecimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora_V0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora_V0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora_V0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora_V0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora_V0().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_0;
    private javax.swing.JButton bt_1;
    private javax.swing.JButton bt_2;
    private javax.swing.JButton bt_3;
    private javax.swing.JButton bt_4;
    private javax.swing.JButton bt_5;
    private javax.swing.JButton bt_6;
    private javax.swing.JButton bt_7;
    private javax.swing.JButton bt_8;
    private javax.swing.JButton bt_9;
    private javax.swing.JButton bt_Borrar;
    private javax.swing.JButton bt_CE;
    private javax.swing.JButton bt_CambiarSigno;
    private javax.swing.JButton bt_Clear;
    private javax.swing.JButton bt_Cuadrado;
    private javax.swing.JButton bt_Decimal;
    private javax.swing.JButton bt_Dividir;
    private javax.swing.JButton bt_Inverso;
    private javax.swing.JButton bt_Multiplicar;
    private javax.swing.JButton bt_Porcentaje;
    private javax.swing.JButton bt_RaizCuadrada;
    private javax.swing.JButton bt_Restar;
    private javax.swing.JButton bt_Resultado;
    private javax.swing.JButton bt_Sumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta_Display;
    // End of variables declaration//GEN-END:variables
}
