
package TEMA10_Colecciones.ejercicios;

/**
 *
 * @author Ruper
 */
public class CapitalesPaises {
    public static final String[] [] pares = {
        // Africa
        {"ALGERIA", "Algiers" } , { "ANGOLA", "Luanda" } ,
        {"BENIN" , " Porto-Novo" } , { "BOTSWANA" , "Gaberone" } ,
        {"BURKINA FASO", "Ouagadougou"} , { "BURUNDI", "Bu jumbura" } ,
        {"CAMEROON", "Yaounde" } , {"CAPE VERDE", "Praia" } ,
        {"CENTRAL AFRICAN REPUBLIC" , "Bangui" } ,
        {"CHAD", "N'dj amena"}, { "COMOROS", "Moroni" } ,
        {"CONGO", "Brazzaville"}, {"DJIBOUTI", "Dijibouti"},
        {"EGYPT", "Cairo" } , {"EQUATORIAL GUINEA", "Malabo"},
        {"ERITREA", "Asmara"}, { "ETHIOPIA", "Addis Ababa"},
        {"GABON", "Libreville"}, { "THE GAMBIA", "Banjul"},
        {"GHANA", "Accra" } , {"GUINEA", "Conakry" } ,
        {"GUINEA", "-" }, {"BISSAU","Bissau"},
        {"CETE DI IVOIR (IVORY COAST)", "Yamoussoukro"},
        {"KENYA", "Nairobi"}, {"LESOTHO", "Maseru"} ,
        {"LIBERIA", "Monrovia"}, {"LIBYA", "Tripoli"} ,
        {"MADAGASCAR"," Antananarivo"}, { "MALAWI'","Lilongwe" },
        {"MALI"," Bamako" } , {"MAURITANIA"," Nouakchott"},
        {"MAURITIUS", "Port Louis"}, { "MOROCCO", "Rabat"},
        {"MOZAMBIQUE", "Maputo" } , { "NAMIBIA", "Windhoek"},
        {"NIGER" , "Niamey" } , { "NIGERIA" , "Abuja"},
        {"RWANDA", "Kigali" } , { "SAO TOME E PRINCIPE", "Sao Tome"},
        {"SENEGAL", "Dakar" } , { "SEYCHELLES", "Victoria"},
        {"SIERRA LEONE","Freetown"}, {"SOMALIA","Mogadishu"},
        {"SOUTH AFRICA", "pretoria/Cape Town" } , {"SUDAN", "Khartoum"},
        {"SWAZILAND","Mbabane"}, {"TANZANIA","Dodoma"},
        {"TOGO","Lome"}, {"TUNISIA", "Tunis"},
        {"UGANDA", "Kampala"} ,
        {"DEMOCRATIC REPUBLIC OF THE CONGO (ZAIRE)", "Kinshasa"},
        {"ZAMBIA","Lusaka"}, {"ZIMBABWE","Harare"},
        // Asia
        {"AFGHANISTAN", "Kabul"} , {"BAHRAIN", "Manama"} ,
        {"BANGLADESH","Dhaka"}, {"BHUTAN","Thimphu"},
        {"BRUNEI", "Bandar Seri Begawan"} , {"CAMBODIA", "Phnom Penh"},
        {"CHINA","Beijing"}, {"CYPRUS","Nicosia"},
        {"INDIA", "New Delhi"}, {"INDONESIA", "Jakarta"},
        {"IRAN", "Tehran"} , {"IRAQ", "Baghdad"},
        {"ISRAEL", " Jerusalem" } , {"JAPAN", "Tokyo"},
        {"JORDAN", "Amman"}, {"KUWAIT", "Kuwait City"},
        {"LAOS", "Vientiane"}, {"LEBANON", "Beirut"},
        {"MALAYSIA", "Kuala Lumpur"}, {"THE MALDIVES", "Male"} ,
        {"MONGOLIA", "Ulan Bator"} , {"MYANMAR (BURMA)", "Rangoon" } ,
        {"NEPAL", "Katmandu"} , {"NORTH KOREA", "Pyongyang" } ,
        {"OMAN", "Muscat"}, {"PAKISTAN", "Islamabad"},
        {"PHILIPPINES", "Manila"}, {"QATAR", "Doha"},
        {"SAUDI ARABIA","Riyadh"}, {"SINGAPORE","Singapore"},
        {"SOUTH KOREA","Seoul"}, {"SRI LANKA","Colombo"},
        {"SYRIA", "Damascus"}, {"TAIWAN (REPUBLIC OF CHINA) ", "Taipei" },
        {"THAILAND)", "Bangkok"}, {"TURKEY", "Ankara"},
        {"UNITED ARAB EMIRATES", "Abu Dhabi"}, { "VIETNAM", "Hanoi"},
        {"YEMEN", "Sana'a"},
        // Australia and Oceania
        {"AUSTRALIA", "Canberra"}, { "E1 JI", "Suva" },
        {"KIRIBATI","Bairiki"},
        {"MARSHALL ISLANDS","Dalap-Uliga-Darrit"},
        {"MICRONESIA", "Palikir"} , {"NAURU", "Yaren"} ,
        {"NEW ZEALAND", "Wellington"} , {"PALAU", "Koror" },
        {"PAPUA NEW GUINEA", "Port Moresby"},
        {"SOLOMON ISLANDS", "Honaira"} , {"TONGA", "Nuku'alofa" },
        {"TUVALU","Fongafale"}, {"VANUATU","Port-Vila"},
        {"WESTERN SAMOA", "Apia"},
        // Eastern Europe and former USSR
        {"ARMENIA", "Yerevan"} , {"AZERBAI JAN", "Baku"},
        {"BELARUS (BYELORUSSIA)", "Minsk"} , {"GEORGIA", "Tbilisi"},
        {"KAZAKSTAN", "Almaty" }, {"KYRGYZSTAN", "Alma-Ata"},
        {"MOLDOVA", "Chisinau"}, {"RUSSIA", "Moscow"},
        {"TAJIKISTAN","Dushanbe"}, {"TURKMENISTAN","Ashkabad"},
        {"UKRAINE", "Kyiv" } , {"UZBEKISTAN", "Tashkent"},
        // Europe
        {"ALBANIA", "Tirana"}, {"ANDORRA", "Andorra la Vella" } ,
        {"AUSTRIA", "Vienna"}, {"BELGIUM", "Brussels"},
        {"BOSNIA", "-"} , { "HERZEGOVINA", "Sarajevo" } ,
        {"CROATIA", "Zagreb" } , { "CZECH REPUBLIC", "Prague"},
        {"DENMARK", "Copenhagen" } , {"ESTONIA", "Tallinn"},
        {"FINLAND", "Helsinki"}, {"FRANCE", "Paris"},
        {"GERMANYU","Berlin"}, {"GREECE","Athens"},
        {"HUNGARY", "Budapest"}, {"ICELAND", "Reykjavik"},
        {"IRELAND", "Dublin"}, {"ITALY", "Rome"},
        {"LATVIA", "Riga" } , { "LIECHTENSTEIN", "Vaduz" } ,
        {"LITHUANIA", "Vilnius"} , {"LUXEMBOURG", "Luxembourg"},
        {"MACEDONIA", "Skopje"} , {"MALTA", "Valletta"} ,
        {"MONACO", "Monaco" } , {"MONTENEGRO", "Podgorica" } ,
        {"THE NETHERLANDS", "Amsterdam"} , { "NORWAY", "Oslo" },
        {"POLAND","Warsaw"}, {"PORTUGAL","Lisbon"},
        { "ROMANIA", "Bucharest" } , {"SAN MARINO", "San Marino"},
        {"SERBIA","Belgrade"}, {"SLOVAKIA","Bratislava"},
        {"SLOVENIA","Ljujiana"}, {"SPAIN","Madrid"},
        {"SWEDEN", "Stockholm" } , { "SWITZERLAND", "Berne" },
        {"UNITED KINGDOM", "London"}, { "VATICAN CITY", "---" },
        // North and Central America
        {"ANTIGUA AND BARBUDA", "Saint John's"}, {"BAHAMAS", "Nassau" },
        {"BARBADOS1"," Bridgetown"}, {"BELIZE"," Belmopanl"} ,
        {"CANADA", "Ottawa"}, {"COSTA RICA", "San Jose" } ,
        {"CUBA", "Havana" } , {"DOMINICA", "Roseau"},
        {"DOMINICAN REPUBLIC","Santo Domingo"},
        {"EL SALVADOR", "San Salvador"}, {"GRENADA", "Saint George' S"},
        {"GUATEMALA", "Guatemala City"}, {"HAITI", "Port-au-Prince"},
        {"HONDURAS", "Tegucigalpa"}, {"JAMAICA", "Kingston"},
        {"MEXICO","Mexico City"}, {"NICARAGUA","Managua"},
        {"PANAMA", "Panama City"}, {"ST. KITTS", "-"},
        {"NEVIS", "Basseterre"}, {"SS. LUCIA", "Castries"},
        {"SS. VINCENT AND THE GRENADINES", "Kingstown"} ,
        {"UNITED STATES OF AMERICA", "Washington, D. C. "},
        // South Amcrica
        {"ARGENTINA","Buenos Alres"},
        {"BOLIVIA","Sucre (legal)/La Paz(administrative)"},
        {"BRAZIL","Brasilia"}, {"CHILE","Santiago"},
        {"COLOMBIA", "Bogota"}, {"ECUADOR", "Quito"},
        {"GUYANA","Georgetown"}, {"PARAGUAY","Asuncion"},
        {"PERU", "Lima"}, {"SURINAME", "Paramaribo"},
        {"TRINIDAD AND TOBAGO", "Port of Spain"},
        { "URUGUAY", "Montevideo" } , { "VENEZUELA", "Caracas" } ,
    };

}
