
package TEMA09_InterfacesGraficas.interfaces;

/**
 *
 * @author Ruper
 */
public class Aficiones extends javax.swing.JFrame {

    /**
     * Creates new form Aficiones1
     */
    public Aficiones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_Musica = new javax.swing.JButton();
        bt_Deportes = new javax.swing.JButton();
        bt_Reset = new javax.swing.JButton();
        lb_Aficiones = new javax.swing.JLabel();
        tf_Resultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_Musica.setBackground(new java.awt.Color(51, 255, 255));
        bt_Musica.setText("MUSICA");
        bt_Musica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_MusicaMouseClicked(evt);
            }
        });
        bt_Musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_MusicaActionPerformed(evt);
            }
        });

        bt_Deportes.setBackground(new java.awt.Color(51, 255, 255));
        bt_Deportes.setText("DEPORTES");
        bt_Deportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_DeportesMouseClicked(evt);
            }
        });
        bt_Deportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_DeportesActionPerformed(evt);
            }
        });

        bt_Reset.setBackground(new java.awt.Color(153, 153, 153));
        bt_Reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_Reset.setText("RESET");
        bt_Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_ResetMouseEntered(evt);
            }
        });
        bt_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ResetActionPerformed(evt);
            }
        });

        lb_Aficiones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_Aficiones.setText("AFICIONES");

        tf_Resultado.setBackground(new java.awt.Color(255, 255, 153));
        tf_Resultado.setText("¿Cuál es tu afición?");
        tf_Resultado.setEnabled(false);
        tf_Resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(bt_Musica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(bt_Deportes)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(lb_Aficiones))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(tf_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(bt_Reset)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Musica)
                    .addComponent(bt_Deportes))
                .addGap(47, 47, 47)
                .addComponent(lb_Aficiones)
                .addGap(37, 37, 37)
                .addComponent(tf_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(bt_Reset)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_MusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_MusicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_MusicaActionPerformed

    private void bt_DeportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_DeportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_DeportesActionPerformed

    private void bt_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ResetActionPerformed

    private void tf_ResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ResultadoActionPerformed

    private void bt_MusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_MusicaMouseClicked
        this.tf_Resultado.setText("MUSICA");
    }//GEN-LAST:event_bt_MusicaMouseClicked

    private void bt_DeportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_DeportesMouseClicked
        this.tf_Resultado.setText("DEPORTES");
    }//GEN-LAST:event_bt_DeportesMouseClicked

    private void bt_ResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ResetMouseEntered
        this.tf_Resultado.setText("¿Cual es tu afición");
    }//GEN-LAST:event_bt_ResetMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aficiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aficiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aficiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aficiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aficiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Deportes;
    private javax.swing.JButton bt_Musica;
    private javax.swing.JButton bt_Reset;
    private javax.swing.JLabel lb_Aficiones;
    private javax.swing.JTextField tf_Resultado;
    // End of variables declaration//GEN-END:variables
}
