
package TEMA09_InterfacesGraficas.interfaces;

import java.awt.event.MouseEvent;

/**
 *
 * @author alumno
 */
public class Ejemplo extends javax.swing.JPanel {

    /**
     * Creates new form Ejemplo
     */
    public Ejemplo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_Aceptar = new javax.swing.JButton();
        bt_Cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        bt_Aceptar.setText("Aceptar");
        bt_Aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_AceptarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_AceptarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_AceptarMouseReleased(evt);
            }
        });
        bt_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AceptarActionPerformed(evt);
            }
        });

        bt_Cancelar.setText("Cancelar");
        bt_Cancelar.setActionCommand("Cancelar");
        bt_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelarActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_Aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_Cancelar)))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Aceptar)
                    .addComponent(bt_Cancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    void escribir(String eventoDescripcion, MouseEvent e){
        // Escriba en el area de texto la descripcion que se describe como parametro
        jTextArea1.append(eventoDescripcion + ".\n");
        
        // Comprobar que boton ha sido
        if(e.getComponent().getName().equals(bt_Aceptar.getName()))
            jTextArea1.append("Es el boton Aceptar.\n");
        else
            jTextArea1.append("Es el boton Cancelar.\n");
    }
    
    
    // AQUI EL MAIN
    
    private void bt_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_CancelarActionPerformed

    private void bt_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_AceptarActionPerformed

    private void bt_AceptarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AceptarMousePressed
        escribir("Pulsado en el boton del raton", evt);
    }//GEN-LAST:event_bt_AceptarMousePressed

    private void bt_AceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AceptarMouseClicked
        escribir("Click en el boton del raton", evt);
    }//GEN-LAST:event_bt_AceptarMouseClicked

    private void bt_AceptarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AceptarMouseReleased
        escribir("Liberado en el boton del raton", evt);
    }//GEN-LAST:event_bt_AceptarMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Aceptar;
    private javax.swing.JButton bt_Cancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
